apiVersion: v1
kind: Service
metadata:
  name: springlearning-service
  namespace: springlearning
spec:
  selector:
    app: springlearning
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
